### ISSUE TITLE
App Startup Crash

### ISSUE THREAD

**Issue by usergrin** [lhns/restic-android#138]
Hi everyone, i am experiencing direct crash of the app upon start. Only splash logo shows. This happens after upgrading to 0.4.2.1941* from 0.2.2.1941*, with universal and split-apk. Phone OS Graphene Android 13, Pixel 6.

The following report is in the crash details:

``` type: crash
osVersion: google/oriole/oriole:13/TQ1A.230205.002/2023030400:user/release-keys
package: de.lolhens.resticui:1941588711
process: de.lolhens.resticui
processUptime: 249 + 886 ms

java.lang.RuntimeException: Unable to start activity ComponentInfo{de.lolhens.resticui/de.lolhens.resticui.MainActivity}: android.view.InflateException: Binary XML file line #32 in de.lolhens.resticui:layout/activity_main: Binary XML file line #32 in de.lolhens.resticui:layout/activity_main: Error inflating class fragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3646)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3783)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.view.InflateException: Binary XML file line #32 in de.lolhens.resticui:layout/activity_main: Binary XML file line #32 in de.lolhens.resticui:layout/activity_main: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #32 in de.lolhens.resticui:layout/activity_main: Error inflating class fragment
Caused by: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@7deca34a: getName
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.bluetooth.IBluetoothManager$Stub$Proxy.getName(IBluetoothManager.java:552)
	at android.bluetooth.BluetoothAdapter.getName(BluetoothAdapter.java:1573)
	at de.lolhens.resticui.util.HostnameUtil.detectHostname(HostnameUtil.kt:14)
	at de.lolhens.resticui.BackupManager.initRestic(BackupManager.kt:60)
	at de.lolhens.resticui.BackupManager.<init>(BackupManager.kt:208)
	at de.lolhens.resticui.BackupManager.<init>(Unknown Source:0)
	at de.lolhens.resticui.BackupManager$Companion.instance(BackupManager.kt:28)
	at de.lolhens.resticui.ui.folders.FoldersFragment.onCreateView(FoldersFragment.kt:32)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2888)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3129)
	at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:394)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:260)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:142)
	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:248)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:227)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at de.lolhens.resticui.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:49)
	at de.lolhens.resticui.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:43)
	at de.lolhens.resticui.MainActivity.onCreate(MainActivity.kt:20)
	at android.app.Activity.performCreate(Activity.java:8352)
	at android.app.Activity.performCreate(Activity.java:8331)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1422)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3627)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3783)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.bluetooth.BluetoothManagerService.checkPermissionForDataDelivery(BluetoothManagerService.java:3239)
	at com.android.server.bluetooth.BluetoothManagerService.checkConnectPermissionForDataDelivery(BluetoothManagerService.java:3257)
	at com.android.server.bluetooth.BluetoothManagerService.getName(BluetoothManagerService.java:1942)
	at android.bluetooth.IBluetoothManager$Stub.onTransact(IBluetoothManager.java:256)
	at android.os.Binder.execTransactInternal(Binder.java:1302)
```

If somebody has an idea how to fix this, I would appreciate a lot!

**Comment by lhns** [comment]
fixed in c044f119bdd03de49dd26c8ceed4e7fa63f7cc13
