### ISSUE TITLE
Crash on Android 12 when starting backup

### ISSUE THREAD

**Issue by slowscript** [lhns/restic-android#142]
When I select a folder to backup and press the Backup button the app crashes like this:
```
FATAL EXCEPTION: main
Process: de.lolhens.resticui, PID: 1886
java.lang.IllegalArgumentException: de.lolhens.resticui: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
  at android.app.PendingIntent.checkFlags(PendingIntent.java:377)
  at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:460)
  at android.app.PendingIntent.getActivity(PendingIntent.java:446)
  at android.app.PendingIntent.getActivity(PendingIntent.java:410)
  at de.lolhens.resticui.BackupManager.updateNotification$pendingIntent(BackupManager.kt:97)
  at de.lolhens.resticui.BackupManager.updateNotification(BackupManager.kt:118)
  at de.lolhens.resticui.BackupManager.updateNotification$default(BackupManager.kt:90)
  at de.lolhens.resticui.BackupManager.backup(BackupManager.kt:248)
  at de.lolhens.resticui.BackupManager.backup$default(BackupManager.kt:231)
  at de.lolhens.resticui.ui.folder.FolderFragment.onCreateView$lambda$6(FolderFragment.kt:208)
  at de.lolhens.resticui.ui.folder.FolderFragment.$r8$lambda$5ujabiUaNEHzHkmV9aEW9wPM-dc(Unknown Source:0)
  at de.lolhens.resticui.ui.folder.FolderFragment$$ExternalSyntheticLambda5.onClick(Unknown Source:4)
  at android.view.View.performClick(View.java:7467)
  at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1202)
  at android.view.View.performClickInternal(View.java:7444)
  at android.view.View.access$3700(View.java:840)
  at android.view.View$PerformClick.run(View.java:28830)
  at android.os.Handler.handleCallback(Handler.java:978)
  at android.os.Handler.dispatchMessage(Handler.java:104)
  at android.os.Looper.loopOnce(Looper.java:238)
  at android.os.Looper.loop(Looper.java:357)
  at android.app.ActivityThread.main(ActivityThread.java:8089)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```
Seems like you need to add `FLAG_IMMUTABLE` to your `PendingIntent`s.

**Comment by lhns** [comment]
should be fixed in v0.4.5
